name: ExtDN M2 Integration Tests
on: [ push, pull_request ]
jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    strategy:
      matrix:
        php-version: [ '7.3', '7.4' ]
        version: [ "2.3.6","2.3.6-p1","2.4.1-p1", "2.4.2" ]
        exclude:
          - php-version: extdn/github-actions-m2/magento-integration-tests/7.3@master
            version: [ "2.4.1-p1", "2.4.2" ]
          - php-version: extdn/github-actions-m2/magento-integration-tests/7.4@master
            version: [ "2.3.6", "2.3.6-p1" ]
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      es:
        image: docker.io/wardenenv/elasticsearch:7.8
        ports:
          - 9200:9200
        env:
          'discovery.type': single-node
          'xpack.security.enabled': false
          ES_JAVA_OPTS: "-Xms64m -Xmx512m"
        options: --health-cmd="curl localhost:9200/_cluster/health?wait_for_status=yellow&timeout=60s" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: M2 Integration Tests with Magento Version ${{ matrix.version }} and ${{ matrix.php-version }}
      - if: matrix.php-version == '7.3'
        uses: extdn/github-actions-m2/magento-integration-tests/7.3@master
      - if: matrix.php-version == '7.4'
        uses: extdn/github-actions-m2/magento-integration-tests/7.4@master
        with:
          module_name: Koality_MagentoPlugin
          composer_name: customgento/module-koality-m2
          ce_version: ${{ matrix.version }}
